const List<String> alertTypes = [
  "Air Quality Alert",
  "Air Stagnation Advisory",
  "Blizzard Warning",
  "Blowing Dust Advisory",
  "Blowing Dust Warning",
  "Brisk Wind Advisory",
  "Cold Weather Advisory",
  "Dense Fog Advisory",
  "Dense Smoke Advisory",
  "Dust Advisory",
  "Dust Storm Warning",
  "Evacuation Immediate",
  "Extreme Heat Warning",
  "Extreme Heat Watch",
  "Extreme Cold Warning",
  "Extreme Cold Watch",
  "Extreme Fire Danger",
  "Extreme Wind Warning",
  "Fire Warning",
  "Fire Weather Watch",
  "Flash Flood Statement",
  "Flash Flood Warning",
  "Flash Flood Watch",
  "Flood Advisory",
  "Flood Statement",
  "Flood Warning",
  "Flood Watch",
  "Freeze Warning",
  "Freeze Watch",
  "Freezing Fog Advisory",
  "Frost Advisory",
  "Heat Advisory",
  "High Wind Warning",
  "High Wind Watch",
  "Ice Storm Warning",
  "Law Enforcement Warning",
  "Local Area Emergency",
  "Red Flag Warning",
  "Severe Thunderstorm Warning",
  "Severe Thunderstorm Watch",
  "Severe Weather Statement",
  "Shelter In Place Warning",
  "Snow Squall Warning",
  "Special Weather Statement",
  "Tornado Warning",
  "Tornado Watch",
  "Wind Advisory",
  "Winter Storm Warning",
  "Winter Storm Watch",
  "Winter Weather Advisory"
]; 