// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDufC07oD1V0UWRTv3-blTy6uiW4K7KJoc',
    appId: '1:261712958015:android:d4d20b784bf7c8aabe9e8a',
    messagingSenderId: '261712958015',
    projectId: 'sodak-weather-app',
    databaseURL: 'https://sodak-weather-app-default-rtdb.firebaseio.com',
    storageBucket: 'sodak-weather-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ml9q0lO2iDjAQPR2O15nY51G5S3EXRE',
    appId: '1:261712958015:ios:ec2d1b835779f1e5be9e8a',
    messagingSenderId: '261712958015',
    projectId: 'sodak-weather-app',
    databaseURL: 'https://sodak-weather-app-default-rtdb.firebaseio.com',
    storageBucket: 'sodak-weather-app.firebasestorage.app',
    iosBundleId: 'com.sodakweather.ios',
  );
}
